// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO8Rj4m8NEEtPFHqwalttkQKOWdrrDpj0',
    appId: '1:951306724296:web:638db1f0eed4d5a87016fd',
    messagingSenderId: '951306724296',
    projectId: 'e-commerce01-fe9d6',
    authDomain: 'e-commerce01-fe9d6.firebaseapp.com',
    storageBucket: 'e-commerce01-fe9d6.appspot.com',
    measurementId: 'G-V9S7SXDTZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHkyAmHdrha6kF0rfkqp5_vZ7qFbvTHck',
    appId: '1:951306724296:android:0a0c2949207479d37016fd',
    messagingSenderId: '951306724296',
    projectId: 'e-commerce01-fe9d6',
    storageBucket: 'e-commerce01-fe9d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAze_QEIC8IgeTwQoczlt0yZOf3LYfSeKU',
    appId: '1:951306724296:ios:ecd2bf96d1d78f7e7016fd',
    messagingSenderId: '951306724296',
    projectId: 'e-commerce01-fe9d6',
    storageBucket: 'e-commerce01-fe9d6.appspot.com',
    iosClientId: '951306724296-atgpagokhqo4ln77brr70eum6k2382rd.apps.googleusercontent.com',
    iosBundleId: 'com.itiswd.ecommerce01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAze_QEIC8IgeTwQoczlt0yZOf3LYfSeKU',
    appId: '1:951306724296:ios:dc72b33118665e7c7016fd',
    messagingSenderId: '951306724296',
    projectId: 'e-commerce01-fe9d6',
    storageBucket: 'e-commerce01-fe9d6.appspot.com',
    iosClientId: '951306724296-kmjqcp80iqpe2sml2o3l31asna333gng.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
